version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "monodb"
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/dbdata
      - POSTGRES_DB=nfactorvault
    volumes:
      - ./dbdata:/dbdata
  monoservice:
    build:
      context: .
      dockerfile: cmd/monoservice/Dockerfile
      args:
        app_env: DEV
        pg_host: db
        pg_port: 5432
        pg_user: docker
        pg_pwd: docker
        pg_dbname: nfactorvault
    environment:
      WAIT_HOSTS: db:5432
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
volumes:
  dbdata: